---
cisco3:
  device_type: cisco_ios
  host: cisco3.lasthop.io
  username: pyclass
  password: 88newclass

cisco4:
  device_type: cisco_ios
  host: cisco4.lasthop.io
  username: pyclass
  password: 88newclass

arista1:
  device_type: arista_eos
  host: arista1.lasthop.io
  username: pyclass
  password: 88newclass
  global_delay_factor: 5

arista2:
  device_type: arista_eos
  host: arista2.lasthop.io
  username: pyclass
  password: 88newclass
  global_delay_factor: 5

arista3:
  device_type: arista_eos
  host: arista3.lasthop.io
  username: pyclass
  password: 88newclass
  global_delay_factor: 5

arista4:
  device_type: arista_eos
  host: arista4.lasthop.io
  username: pyclass
  password: 88newclass
  global_delay_factor: 5

srx2:
  device_type: juniper_junos
  host: srx2.lasthop.io
  username: pyclass
  password: 88newclass

nxos1:
  device_type: cisco_nxos
  host: nxos1.lasthop.io
  username: pyclass
  password: 88newclass
  port: 22

nxos2:
  device_type: cisco_nxos
  host: nxos2.lasthop.io
  username: pyclass
  password: 88newclass
  port: 22


cisco:
  - cisco3
  - cisco4

arista:
  - arista1
  - arista2
  - arista3
  - arista4

juniper:
  - srx2

nxos:
  - nxos1
  - nxos2
