---
cisco3:
    hostname: cisco3.lasthop.io
    groups:
      - ios

cisco4:
    hostname: cisco4.lasthop.io
    groups:
      - ios

nxos1:
    hostname: nxos1.lasthop.io
    groups:
      - nxos
    data:
      loopbacks:
        - id: 123
          description: ntp source1
          ip: 1.2.3.1
          mask: 255.255.255.255

nxos2:
    hostname: nxos2.lasthop.io
    groups:
      - nxos
    data:
      loopbacks:
        - id: 124
          description: ntp source2
          ip: 1.2.3.2
          mask: 255.255.255.255

arista1:
    hostname: arista1.lasthop.io
    groups:
      - eos

arista2:
    hostname: arista2.lasthop.io
    groups:
      - eos

arista3:
    hostname: arista3.lasthop.io
    groups:
      - eos

arista4:
    hostname: arista4.lasthop.io
    groups:
      - eos

srx2:
    hostname: srx2.lasthop.io
    groups:
      - junos
