---
#logging:
#  enabled: True
#  level: DEBUG
#  file: nornir.log
#  to_console: True

inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "~/nornir_inventory/hosts.yaml"
    group_file: "~/nornir_inventory/groups.yaml"
    defaults_file: "./defaults.yaml"
